version: '3.4'

services:
  eduquest_api:
    image: ${DOCKER_REGISTRY-}eduquestapi
    build:
      context: .
      dockerfile: EduQuest_API/Dockerfile
    ports: 
        - "7205:8081"
  redis:
    image: redis:latest
    container_name: redis_edu_quest
    ports:
        - "6379:6379"
