version: '3.4'

services:
  eduquest_api:
    image: ${DOCKER_REGISTRY-}eduquestapi
    build:
      context: .
      dockerfile: EduQuest_API/Dockerfile
    ports: 
        - "5126:8080"
        - "7205:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_USE_POLLING_FILE_WATCHER=1
  redis:
    image: redis:latest
    container_name: redis_edu_quest
    ports:
        - "6379:6379"
